openthread/ot-efr32

third_party/silabs/cmake/imported_libs.cmake

Also, update openthread commit
Mirrors https://github.com/openthread/openthread/pull/6328

[cmake] switch imported_libs.cmake to NAME_WE to stay compliant with cmake 3.10

---

script/build

This was previously done in [openthread](https://github.com/openthread/openthread/blob/main/script/cmake-build#L177) and prevents errors that arise when build different platforms consecutively.
For example, building `efr32mg1` then `efr32mg21` will cause the MG21 build to fail because binaries were previously compiled using different floating point formats for MG1 that are incompatible with MG21
```shell
arm-none-eabi/bin/ld: error: ../third_party/silabs/gecko_sdk_suite/v3.1/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a(nvm3_page.o) uses VFP register arguments, bin/ot-ncp-ftd does not
arm-none-eabi/bin/ld: failed to merge target specific data of file ../third_party/silabs/gecko_sdk_suite/v3.1/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a(nvm3_page.o)
```

[build] create platform subdir in `build` folder

---

.github/dependabot.yml

To enable automatic daily updates of openthread submodule.
Will wait for GitHub Actions build checks before merging.

[dependabot] add config file

---

.github/dependabot.yml

@romacdon would like to have me be the one approving dependabot PRs. This will save him some email spam

[dependabot] remove `romacdon` from PR reviewers

---

src/src/uart.c

In this commit, I have:
* Fixed a bug in otPlatUartFlush() where flushTimedOut was not set correctly..
* Removed call to otPlatUartFlush() from otPlatUartSend() as this should not be required.
* Renamed sCheckForTxComplete to sTxComplete
* Also updated otPlatUartFlush() to clear out sTxComplete flag once the flush is complete

[uart] updates to otPlatUartSend & otPlatUartFlush 

---

src/src/mbedtls_config.h
third_party/silabs/cmake/mbedtls.cmake

This commit adds missing preprocessor definition to fix build error
when ECDSA and SRP_CLIENT options are enabled.
Tested with following build flags:
```
./script/cmake-build efr32mg12 -DBOARD=brd4166a -DOT_COAP=ON -DOT_ECDSA=ON -DOT_SRP_CLIENT=ON
```
Fixes https://github.com/openthread/openthread/issues/6549

[mbedtls] fix build issue when ECDSA, SRP_CLIENT enabled (#6549)

---

README.md
src/README.md

Added warning concerning mismatching versions and potential compatibility issues for RCP & OTBR use cases with mismatched OpenThread versions and when mixing projects from GitHub repos with the Silabs GSDK (ex: building either RCP or OTBR with GSDK and using GitHub repos for the other project).

[docs] add warning concerning mismatched versions, RCP and OTBR

---

CMakeLists.txt

This commit sets the version git hash to this repo, rather than the
openthread repo.

[camke] set default package version to git hash of root

---

script/build

This adds `--skip-silabs-apps` which will cause the build script to skip over any Silicon Labs apps.
```shell
usage: ./script/build [-h] [--skip-silabs-apps] <efr32 platform> -DBOARD=<brdXXXXy> [-D<OT_XXXX=ON> -D<OT_YYYY=OFF>]
```
```shell
$ ./script/build --skip-silabs-apps efr32mg12 -DBOARD=brd4161a
....
-- Build files have been written to: /home/mason/repos/ot-reference-release/ot-efr32/build/efr32mg12
+ [[ -n ot-rcp ot-cli-ftd ot-cli-mtd ot-ncp-ftd ot-ncp-mtd ]]
+ ninja ot-rcp ot-cli-ftd ot-cli-mtd ot-ncp-ftd ot-ncp-mtd
[187/187] Linking CXX executable bin/ot-ncp-ftd
.....
```

[build] add flag to allow skipping silabs apps

---

examples/sleepy-demo/README.md
examples/sleepy-demo/sleepy-demo-mtd/main.c

MTD Changes
- Change link polling period to 2000ms
- Disable mode change upon becoming a child. This is to match the behavior of the Gecko SDK sleepy-demo-mtd app

[examples] update sleepy-demo-mtd to match behavior in the GSDK implementation

---

src/src/platform-band.h
src/src/radio.c

This aligns the RAIL TX buffer to the appropriate memory alignment for each specific series of chips.

[radio] align RAIL TX buffer to appropriate memory alignment

---

examples/sleepy-demo/README.md
examples/sleepy-demo/sleepy-demo-ftd/main.c
examples/sleepy-demo/sleepy-demo-mtd/main.c

This removes LED support from the sleepy-demo example apps
Some boards have limited GPIO and, as a result, button 0 and LED 0 share the same pin. The same is true for button 1 and LED 1 on these boards.
Instead of special-casing, the decision was made to just remove LEDs from the apps.
Users will still be able to see button presses by monitoring the CLI output of both apps﻿

[examples] remove LEDs from sleepy-demo

---

script/build

This switches to using `efr32_check_platform` to check if a platform is valid. This should fix the issues with broken pipes that the CI is running into.
Fixes #246

[build] fix platform validity check

---

.github/workflows/build.yml

We've used ~5.3TB of bandwidth in the last month. This is because every GitHub action is pulling the Git LFS objects unconditionally.
The implementation is from: actions/checkout#165

[github-actions] cache git LFS directory

---

src/src/sleep.h
src/src/system.c

Currently if a user generates the platform library using the `power_manager` component, the build will throw a warning in [`otSysProcessDrivers()`](https://github.com/openthread/ot-efr32/blob/41d97122ff121afaaf1c4b2f8274f7d2537ca21a/src/src/system.c#L154-L157) because the header for `sl_power_manager_sleep()` is missing.
This fixes it and also fixes a missing `stdbool.h` include

[platform] fix bugs when building platform libs with power manager

---

src/src/system.c

This fixes a freeRTOS assert due to the device going to sleep unexpectedly since freeRTOS is supposed to be managing when the device goes to sleep

[sleep] only call sl_power_manager_sleep() in baremetal environment

---

src/src/radio.c

For scheduled-rx config, set rxTransitionEndSchedule=1 to idle after scheduled-rx operation. [Required after GSDK 4.1.0 update for EFR32]

[efr32] fix PAL scheduled-rx parameter

---

examples/sleepy-demo/README.md

Previous link was broken, as it pointed to a section that wouldn't resolve.
This change updates the README path and the section label to resolve the link.

Fix sleepy demo README link for flashing binaries

---

src/src/radio.c

This change replaces a hardcoded TX PA ramp time value with a RAIL macro in the platform configuration procedure, which will allow RAIL to configure the ramp time to a user specified value.

[radio] Replace hardcoded TX power ramp time with macro

---

script/build_example_apps

[A change](https://github.com/openthread/openthread/pull/7979/files#diff-2dfd8d58f7ec7b21e573c09220dc27e20c77fb6fea1afd92e370c90b1a8f4f8aR121) from https://github.com/openthread/openthread/pull/7979 makes it so that `OT_PING_SENDER`'s default value is `OT_APP_CLI` which is a CMake option that's used to enable/disable building of the `ot-cli-ftd`.
This PR explicitly turns on `OT_PING_SENDER` when building the `sleepy-demo` apps

[examples] enable `ping` in sleepy-demo apps

---

script/build
script/build_example_apps

This fixes concurrency issues in CI where multiple SLC instances may be running, where each may be using a different sdk

[build] add `-data` flag to slc calls

---

.github/workflows/build.yml

`actions/cache@v2` uses some depracated commands. https://github.com/openthread/ot-efr32/actions/runs/3284516083/jobs/5410564966#step:4:6
This updates to `actions/cache@v3` which should fix the warning

[actions] update `actions/cache` to `v3`

---

.github/workflows/build.yml
.gitignore

I've been seeing SLC generation failing intermittently both in GitHub Actions ([example](
https://github.com/openthread/ot-efr32/actions/runs/4561484245/jobs/8047495581?pr=547)) and in our internal Jenkins server.
Adding this for more debug data on failures.

[actions] upload build artifacts on failure

---

.github/workflows/docker.yml
Dockerfile
script/bootstrap
script/generate_cmake.py

This adds a step in the docker workflow that runs `script/test` inside a container created using the newly built `siliconlabsinc/ot-efr32-dev` image before pushing the image to Docker Hub.
Other Changes:
- [actions] use cache for lfs pull in docker workflow
- (related to openthread/ot-efr32#336)
- [script] update [`script/bootstrap`](https://github.com/openthread/ot-efr32/pull/619/files#diff-2ad9e188678c4f3bef503efff261066b6c9df3a948bcaabe8bc10bdd2f45404a) java version due to SLC requiring Java 17
- [script] update [`script/generate_cmake.py`](https://github.com/openthread/ot-efr32/pull/619/files#diff-64f5739113084f2c5ddf82cab14384806594d7c83f6f371463200631dfff9796) to work when repo sources are not in a git environment (ie when downloaded as a .zip)
- (related to openthread/ot-efr32#566)

[docker] test docker image before pushing

---

.github/workflows/docker.yml

- Use the GitHub Actions cache to speed up the docker image build
- Example of a run that was able to leverage the GHA cachehttps://github.com/SiliconLabs/ot-efr32/actions/runs/5386100907/jobs/9775793390#step:9:149
- Reduce scope of testing for the docker image
- Running `script/build` on a single board is enough to tell us whether the image works as intended or not

[actions] use github actions cache for docker build

---

.github/workflows/build.yml

Running the `arm-gcc` builds inside of `siliconlabsinc/ot-efr32-dev` will improve reliability

[actions] run `arm-gcc` job inside of `siliconlabsinc/ot-efr32-dev`

---

examples/sleepy-demo/CMakeLists.txt
examples/sleepy-demo/README.md
examples/sleepy-demo/sleepy-demo-ssed.cmake
examples/sleepy-demo/sleepy-ssed.c
script/build_example_apps
src/platform_projects/openthread-efr32-rcp-spi.slcp
src/platform_projects/openthread-efr32-rcp-uart.slcp
src/platform_projects/openthread-efr32-soc-with-buttons-power-manager-csl.slcp
src/platform_projects/openthread-efr32-soc-with-buttons-power-manager.slcp
src/platform_projects/openthread-efr32-soc-with-buttons.slcp

This adds a new example app `sleepy-demo-ssed` that functions similarly to the `sleepy-demo-mtd` app, with the exception that it uses CSL instead of polling.
The example app is meant to be used in tandem with the `sleepy-demo-ftd` app

[examples] add `sleepy-demo-ssed`

---

.github/workflows/build.yml
examples/example_vendor_slc_extension/projects/example-vendor-rcp-spi.slcp
examples/example_vendor_slc_extension/projects/example-vendor-rcp-uart.slcp
examples/example_vendor_slc_extension/projects/example-vendor-soc-with-buttons.slcp
examples/example_vendor_slc_extension/projects/example-vendor-soc.slcp
ot-efr32.slce
script/bootstrap
slc/component/ot_stack_features_config.slcc
src/platform_projects/openthread-efr32-rcp-spi.slcp
src/platform_projects/openthread-efr32-rcp-uart.slcp
src/platform_projects/openthread-efr32-soc-with-buttons-power-manager-csl.slcp
src/platform_projects/openthread-efr32-soc-with-buttons-power-manager.slcp
src/platform_projects/openthread-efr32-soc-with-buttons.slcp
src/platform_projects/openthread-efr32-soc.slcp
src/src/alarm.c
src/src/crypto.c
src/src/diag.c
src/src/ieee802154-packet-utils.cpp
src/src/logging_rtt.c
src/src/misc.c
src/src/openthread-core-efr32-config.h
src/src/platform-band.h
src/src/platform-efr32.h
src/src/radio.c
src/src/rail_config.h
src/src/sl_rcp_gp_interface.c
src/src/sleep.c
src/src/soft_source_match_table.c

This updates the repo to work with the [Gecko SDK v4.4.0](https://github.com/SiliconLabs/gecko_sdk/releases/tag/v4.4.0) release
---
- Update scripts to install ARM GNU Toolchain 12
- `arm-none-eabi-gcc 12` is a requirement of GSDK v4.4.0
- Removed older toolchains from `Build` workflow
- Add ot_stack_features_config component to ot-efr32 extension
- This adds a new component that generates a config file for `SL_OPENTHREAD_STACK_FEATURES_CONFIG_FILE`
- This is essentially a copy of the ot_stack_ftd/mtd/rcp components except it doesn't define a `OPENTHREAD_<DEVICE_TYPE>` macro
https://github.com/SiliconLabs/gecko_sdk/blob/124fa19de8c8b3961d21c20857f7df32239786da/protocol/openthread/component/ot_stack_ftd.slcc#L21-L26
- The component also uses the [validation …

[sdk] update to GSDK 4.4.0

---

script/build
src/src/radio.c

[This](https://github.com/openthread/ot-efr32/pull/756/files#diff-5e9808c35ace5ab51673c2a099131b5480e0220c41bcc1ccdf5141ef5a3e25e3L1650) deletion should not have happened in `[sdk] update to GSDK 4.4.0` #756 
It caused issues with transmitting secure packets and prevented devices from joining networks.
This PR also includes a diff that was missed in #756 and a minor script fix

[radio] fix connectivity issues caused by an accidental deletion in `radio.c`

---

.dockerignore
.github/workflows/build.yml
.github/workflows/docker.yml
Dockerfile
docker/Dockerfile
docker/test-ot-efr32-dev.yml
script/bootstrap
script/bootstrap_silabs

This PR makes various improvements to the build of the `siliconlabsinc/ot-efr32-dev` docker image
- Remove usage of `openthread/script/bootstrap`. This will provide more control over what goes into the docker image
- Add sanity checks after building the docker image
- Link ARM toolchain and SLC executables to `/usr/local/bin` if the bootstrap scripts are run as `root`
- General improvements to `Dockerfile`

[github-actions][docker] misc. improvements to docker image build

---

script/bootstrap
script/build

This fixes the issue users run into in the scenario below.
1. A user without `git-lfs` installed clones the repo.
2. They run `script/bootstrap` to install required packages, including `git-lfs`.
3. They run `git submodule update --init --recursive .` to init all submodules, including `third_party/silabs/gecko_sdk`
4. They attempt to build example apps `script/build <brdXXXXy>`
5. The build will fail when the linker tries linking `.a` libs from `gecko_sdk` which are lfs objects that haven't been pulled yet
```shell
$ script/build brd4151a
...
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld:/ot-efr32/third_party/silabs/gecko_sdk/platform/radio/rail_lib/autogen/librail_release/librail_efr32xg1_gcc_release.a: file …
```

[script] add pre-build checks that ensure the GSDK submodule has been pulled properly

---

.github/workflows/docker.yml

A bug was introduced in openthread/ot-efr32#793 where I moved `Dockerfile` to `docker/Dockerfile` but did not update both the build steps in the docker workflow, causing [this failure](https://github.com/SiliconLabs/ot-efr32/actions/runs/8468125501/job/23200371772#step:13:126).
This fixes the bug by specifying the new location of the Dockerfile in the `Build and push` step.

[github-actions] fix 'Build and push' step of docker workflow

---

CMakeLists.txt
script/build
script/build_example_apps
script/efr32-definitions

Minor script improvements and also minor changes to the CMakeLists.txt file that make it easier for ot-efr32 to be consumed by a different project

[script] simplify how platform libs are pulled into the CMake build tree

---

script/generate
script/util

Mac platforms are become more locked-down and when grep is installed
by XCode for example it is a BSD version not GNU version so doesn't
have the "-P" option to use perl patterns.  This fixes scripts to not
depend on GNU grep.

Use regular (not Perl) grep syntax in scripts

---

.github/workflows/build.yml
.github/workflows/docker.yml
.github/workflows/metadata.yml
.gitignore
docker/Dockerfile
docker/base.Dockerfile
docker/ot-efr32-dev.Dockerfile
script/bootstrap

This changes the relationship of the workflows so that the `arm-gcc` job in `build.yml` is run using the docker image generated by the `Docker / Build` job.
Previously, the `arm-gcc` job would just use the `:latest` tag of `siliconlabsinc/ot-efr32-dev` from DockerHub. This presents a problem when there are changes to the bootstrap script which are required for the build script to succeed. These changes would not be present in the currently published `siliconlabsinc/ot-efr32-dev:latest` since that image was build off of `SiliconLabs/ot-efr32:main`, not the current branch.

[github-actions] build docker image then run `arm-gcc` with it

---

.github/workflows/build.yml
script/bootstrap
script/build
script/build_example_apps
script/generate

- `slc`
- Remove the `--clear-cache` flag to leverage SDK cache
- Switch to using daemon-mode. Reduces `slc` startup time
- Add [`ccache`](https://ccache.dev/) to build scripts for potential build speedups. See more below
- GitHub Actions
- Only pull required LFS files
- Cache ARM Toolchain between builds
---
When building with no compiler cache, the build proceeds as normal and takes a normal amount of time. For the `Build/arm-gcc-*` workflows, it usually takes ~20-30 min for the workflow to run completely. 
**Example:** `Build/arm-gcc-12.2.Rel1` (no compiler cache)
> If you examine [this](https://github.com/SiliconLabs/ot-efr32/actions/runs/9308159746/job/25620968130?pr=723) run, you can see during the setup, there's no cache found [(log …

[script] leverage `slc` SDK cache and add `ccache` to speedup incremental builds

---

.github/workflows/build.yml
.github/workflows/docker.yml
.github/workflows/dockerhub-publish.yml

Also, this fixes the bug where the DockerHub username and password secrets are unavailable in the DockerHub login step.
[This failure](https://github.com/SiliconLabs/ot-efr32/actions/runs/9681942492/job/26713977695) is caused by a bug I accidentally introduced in https://github.com/openthread/ot-efr32/pull/896. The secrets consumed by a reusable workflow must be defined as inputs.
See this for more details
https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

[github-actions] move DockerHub publish job into a separate workflow

---

CMakeLists.txt
examples/example_vendor_slc_extension/component/my_custom_board.slcc
examples/example_vendor_slc_extension/config.yml
examples/sleepy-demo/README.md
src/README.md

This fixes some leftovers I missed from https://github.com/openthread/ot-efr32/pull/918
---
- Replace `brd4161a` with `brd4186c` in all documentation
- Remove `efr32mg12` subghz support logic from top-level `CMakeLists.txt`

[doc][cmake] update series 1 references to series 2

---

script/bootstrap

`ninja` is the correct brew package name for the Ninja build system
https://formulae.brew.sh/formula/ninja

[script] fix incorrect package name for brew bootstrap
